# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0845c28bdd7b5d30d820c4fac632c5ec71c07fe5317d304bf0148c0dea963e2a84a4c96febaee27cdc17e9e3ab9db7e95a374aa796ac6b8b850a8d49b90b6170

test:
  secret_key_base: 67d720361b2e1e633f095985353424910b499079631f3b18d7239bddcbf4c37696a7df57bd2cee94e96a11f2632ea0e470b1187ed040dcde6b3b748ec0db4cf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
